//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Periodni_Sustav_Elemenata.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Periodni_Sustav_Elemenata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap g_de {
            get {
                object obj = ResourceManager.GetObject("g_de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap g_hr {
            get {
                object obj = ResourceManager.GetObject("g_hr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap g_uk {
            get {
                object obj = ResourceManager.GetObject("g_uk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hr {
            get {
                object obj = ResourceManager.GetObject("hr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///H
        ///Wasserstoff
        ///-259.16
        ///-252.879
        ///explosives Gas, leichtestes Element
        ///90% der Atome im Universum, Sonne und Sterne, H2O, organische Moleküle des Lebens
        ///2
        ///He
        ///Helium
        ///-273.15
        ///-268.928
        ///Inertgas, zweit-leichtestes Element
        ///Kernfusion in Sonne und Sternen, Ballons, Laser, superkaltes Kältemittel
        ///3
        ///Li
        ///Lithium
        ///180,50
        ///1330
        ///leichtestes Metall, weich, reaktiv
        ///leichte Aluminiumlegierungen, Batterien, schlagfestes Keramikkochgeschirr (Corningware®), Stimmungsstabilisator
        ///4
        ///Be
        ///Beryllium
        ///1287
        ///2469
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pse_de {
            get {
                return ResourceManager.GetString("pse_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///H
        ///Hydrogen
        ///-259.16
        ///-252.879
        ///explosive gas, lightest element
        ///90% of atoms in the universe, sun and stars, H2O, life&apos;s organic molecules
        ///2
        ///He
        ///Helium
        ///-273.15
        ///-268.928
        ///inert gas, second-lightest element
        ///nuclear fusion in sun and stars, balloons, lasers, supercold refrigerant
        ///3
        ///Li
        ///Lithium
        ///180.50
        ///1330
        ///lightest metal, soft, reactive
        ///lightweight aluminum alloys, batteries, impact-resistant ceramic cookware (Corningware©), mood stabilizer
        ///4
        ///Be
        ///Beryllium
        ///1287
        ///2469
        ///lightweight metal
        ///non-sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pse_en {
            get {
                return ResourceManager.GetString("pse_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///H
        ///Vodik
        ///-259,16
        ///-252,879
        ///eksplozivni plin, najlakši element
        ///90% atoma u svemiru, suncu i zvijezdama, H2O, životnim organskim molekulama
        ///2
        ///He
        ///helijum
        ///-273,15
        ///-268,928
        ///inertni plin, drugi najlakši element
        ///nuklearna fuzija na suncu i zvijezdama, baloni, laseri, superkrstarena rashladna tekućina
        ///3
        ///Li
        ///litij
        ///180,50
        ///1330
        ///najlakši metal, mekan, reaktivan
        ///lagane aluminijske legure, baterije, keramičke posude za kuhanje otporne na udarce (CorningwareŠ), stabilizator raspoloženja
        ///4
        ///Be
        ///Beriliju [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pse_hr {
            get {
                return ResourceManager.GetString("pse_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uk {
            get {
                object obj = ResourceManager.GetObject("uk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
